# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Discourse:
  fields:
    #default: subject, position #, text, author, assigner, is_moderated
    default: subject, section, kind, position, author, assigner, is_moderated
    form: section, subject, text, kind, author, assigner, position, is_moderated
  order_by: section_id, position
  relationships: assigner, author, section
  filters: created_at
  search: 
  application: chebit
  options:
    action_after_save: index

Section:
  fields:
    default: name, position
    form: name, desc, position
  order_by: position
  # relationships: discourses
  application: chebit
  options:
    action_after_save: index

User:
  fields:
    default: email, last_sign_in_at, full_name, firm, website, occupation, twitter, tel
    form: email, reset_password_token, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip, confirmation_token, confirmed_at, confirmation_sent_at, authentication_token, full_name, firm, website, occupation, note, discourse_state, discourse_subject, price_confirm, twitter, tel
  order_by: created_at
  relationships: assigned_discourses, authored_discourses, base_tags, tag_taggings, taggings, tags
  filters: created_at
  search: 
  application: chebit

