# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Discourse:
  fields:
    #default: subject, position #, text, author, assigner, is_moderated
    default: subject, section, kind, position, author, assigner, is_moderated
    form: section, subject, text, kind, author, assigner, position, is_moderated
    options:
      selectors: kind
  order_by: section_id, position
  relationships: assigner, author, section
  filters: created_at
  search: 
  application: chebit
  options:
    action_after_save: index

Section:
  fields:
    default: name, position
    form: name, desc, position, show
  order_by: position
  # relationships: discourses
  application: chebit
  options:
    action_after_save: index

User:
  fields:
    default: full_name, email, last_sign_in_at, invest_money, firm, website, occupation, tel
    form: full_name, email, firm, website, occupation, note, tel, twitter, invest_money, tag_list
  order_by: created_at
  # relationships: assigned_discourses, authored_discourses, base_tags, tag_taggings, taggings, tags
  filters: created_at
  search: 
  application: chebit

