# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Conference:
  fields:
    default: name, date, is_passed
    form: name, date, is_passed, desc
  order_by: -date
  application: chebit
  relationships: sections
  actions:
    show: show
  options:
    default_action_on_item: edit
    action_after_save: index

ConferenceSection:
  fields:
    default: conference, section, position
  relationships: conference, section
  order_by: -conference_id, position
  options:
    action_after_save: index
  application: chebit


Discourse:
  fields:
    #default: subject, position #, text, author, assigner, is_moderated
    default: conference_section, subject, section, assigner, is_moderated, position
    form: subject, conference_section, section, text, kind, author, assigner, position, is_moderated
    options:
      selectors: kind
  order_by: conference_section_id, section_id, position
  relationships:
  filters: conference_section, section
  search:
  application: chebit
  options:
    per_page: 50
    action_after_save: index

Section:
  fields:
    default: name
    form: name, desc, show
  order_by: id
  relationships: conference_sections
  application: chebit
  options:
    action_after_save: index

User:
  fields:
    default: full_name, email, last_sign_in_at, invest_money, firm, website, occupation, tel
    form: full_name, email, firm, website, occupation, note, tel, twitter, invest_money, tag_list
  order_by: created_at
  # relationships: assigned_discourses, authored_discourses, base_tags, tag_taggings, taggings, tags
  filters: created_at
  search:
  application: chebit

Comment:
  fields:
    default: content 
    form: content
  order_by: id
  application: chebit
  options:
    action_after_save: index

