# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Conference:
  fields:
    default: name, date, registration_at, start_at, finish_at, is_passed
    form: name, date, place, address, registration_at, start_at, break_at, break_length, finish_at, is_passed, desc
  order_by: -date
  application: chebit
  relationships: conference_sections, registrations
  actions:
    show: show
  options:
    default_action_on_item: edit
    action_after_save: index

ConferenceSection:
  fields:
    default: conference, section, position
  order_by: -conference_id, position
  options:
    action_after_save: index
  application: chebit


Discourse:
  fields:
    #default: subject, position #, text, author, assigner, is_moderated
    default: conference_section, subject, section, presenters, time_length, is_moderated, position
    form: subject, conference_section, section, text, kind, author, time_length, position, is_moderated
    options:
      selectors: kind
  order_by: conference_section_id, section_id, position
  relationships: presenters_users
  filters: conference_section, section
  search: subject, text
  application: chebit
  options:
    per_page: 50
    action_after_save: index

Section:
  fields:
    default: name
    form: name, desc, show
  order_by: id
  relationships: conference_sections
  application: chebit
  options:
    action_after_save: index

Registration:
  fields:
    default: conference, user
    form: conference, user
  order_by: conference_id
  relationships: conference, user
  application: chebit
  options:
    action_after_save: create

User:
  fields:
    default: full_name, email, firm, occupation, tel
    form: full_name, email, password, firm, website, occupation, note, tel, twitter, invest_money, tag_list
  order_by: full_name
  relationships: registrations, discourses #assigned_discourses, authored_discourses, base_tags, tag_taggings, taggings, tags
  filters: created_at
  search: full_name, email, firm
  options:
    per_page: 50
  application: chebit

Comment:
  fields:
    default: content
    form: content
  order_by: id
  application: chebit
  options:
    action_after_save: index

